### ISSUE TITLE
Add setup hint for Atlas users: ssl: true + authsource: admin needed in my_launchpad.yaml

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/atomate#635]
Would it be possible to add a note to the `my_launchpad.yaml` section of [setup docs](https://atomate.org/installation.html) notifying users of MongoDB Atlas that passing the connection test

```sh
lpad -l config/my_launchpad.yaml reset
```

requires adding `ssl: true` and `authsource: admin` to `my_launchpad.yaml`

```yml
host: mongodb+srv://atomate-cluster.<DB_ID>.mongodb.net
port: 27017
name: atomate-cluster
username: janosh
password: foobar
ssl_ca_file: null
logdir: null
strm_lvl: INFO
user_indices: []
wf_user_indices: []
# new
ssl: true # required
authsource: admin # required
```

Without `ssl: true`, I'm getting

```py
pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 607731cd0963ed07169e2ed6, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('atomate-cluster-shard-00-00.q8s9p.mongodb.net', 27017)
```

and without `authsource: admin`, the error is

```py
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0, 'errmsg': 'Authentication failed.', 'code': 8000, 'codeName': 'AtlasError'}
```

Alternatively, perhaps worth considering changing the default `ssl` to `True`.
